defmodule Mix.Tasks.PhxFilament.Install do
  @moduledoc """
  Installs PhoenixFilament admin panel in your Phoenix app.

  ## Usage

      mix phx_filament.install

  ## What it does

  1. Creates an admin Panel module at `lib/{app_web}/admin.ex`
  2. Copies Chart.js vendor asset to `assets/vendor/chart.min.js`
  3. Creates `assets/js/phx_filament_hooks.js` with Chart.js LiveView hook

  Running this task multiple times is safe — it is idempotent.

  ## Manual steps after install

  Add the following to your `router.ex`:

      import PhoenixFilament.Router

      # Inside your browser pipeline scope:
      mount_panel MyAppWeb.Admin

  Add the following to your `assets/js/app.js`:

      import PhxFilamentHooks from "./phx_filament_hooks"
      // Merge into your liveSocket hooks:
      // hooks: {...Hooks, ...PhxFilamentHooks}
  """

  if Code.ensure_loaded?(Igniter) do
    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :phoenix_filament,
        example: "mix phx_filament.install"
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      app_name_camel = app_name |> to_string() |> Macro.camelize()
      web_module = Module.concat([app_name_camel <> "Web"])
      panel_module = Module.concat([web_module, "Admin"])
      brand_name = "#{app_name_camel} Admin"

      igniter
      |> create_panel_module(panel_module, brand_name)
      |> copy_chart_js()
      |> create_chart_hook_file()
    end

    defp create_panel_module(igniter, panel_module, brand_name) do
      path = Igniter.Project.Module.proper_location(igniter, panel_module)

      template_path = Application.app_dir(:phoenix_filament, "priv/templates/admin.ex.eex")

      contents =
        if File.exists?(template_path) do
          EEx.eval_file(template_path,
            assigns: %{
              panel_module: inspect(panel_module),
              brand_name: brand_name
            }
          )
        else
          """
          defmodule #{inspect(panel_module)} do
            use PhoenixFilament.Panel,
              path: "/admin",
              brand_name: "#{brand_name}"

            # Add resources with: mix phx_filament.gen.resource MyApp.Schema
          end
          """
        end

      Igniter.create_new_file(igniter, path, contents)
    end

    defp copy_chart_js(igniter) do
      source = Application.app_dir(:phoenix_filament, "priv/static/vendor/chart.min.js")
      dest = "assets/vendor/chart.min.js"

      if File.exists?(source) do
        contents = File.read!(source)
        Igniter.create_new_file(igniter, dest, contents)
      else
        igniter
      end
    end

    defp create_chart_hook_file(igniter) do
      hook_code = """
      // PhoenixFilament Chart.js Hook
      // Auto-generated by mix phx_filament.install
      //
      // Import and merge this into your app.js:
      //
      //   import PhxFilamentHooks from "./phx_filament_hooks"
      //   let liveSocket = new LiveSocket("/live", Socket, {
      //     hooks: {...Hooks, ...PhxFilamentHooks}
      //   })

      import Chart from "../vendor/chart.min.js"

      const PhxFilamentHooks = {
        PhxFilamentChart: {
          mounted() {
            const config = JSON.parse(this.el.dataset.chart)
            this.chart = new Chart(this.el, config)
          },
          updated() {
            const config = JSON.parse(this.el.dataset.chart)
            this.chart.data = config.data
            this.chart.update()
          },
          destroyed() {
            if (this.chart) this.chart.destroy()
          }
        }
      }

      export default PhxFilamentHooks
      """

      Igniter.create_new_file(igniter, "assets/js/phx_filament_hooks.js", hook_code)
    end
  else
    use Mix.Task

    @shortdoc "Installs PhoenixFilament (requires Igniter)"

    @impl Mix.Task
    def run(_argv) do
      Mix.shell().error("""
      PhoenixFilament installer requires Igniter.

      Add {:igniter, "~> 0.7"} to your deps in mix.exs and run:

          mix deps.get
          mix phx_filament.install
      """)
    end
  end
end
